-- Create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "username" character varying NOT NULL, "password" character varying NOT NULL, PRIMARY KEY ("id"));
